services:
    richardhj.simple_ajax.controller:
        class: SimpleAjax\Controller\SimpleAjaxController
        arguments:
          - "@event_dispatcher"
        calls:
          - [setContainer, ["@service_container"]]
        tags: ['controller.service_arguments']
        public: true

parameters:
    simpleajax.entrypoint: "SimpleAjax.php"
    simpleajax.entrypoint-frontend: "SimpleAjaxFrontend.php"
